config/routes.rb
Rails.application.routes.draw do
  get 'pricelist/index'
  devise_for :users
  resources :users
  resources :fractions

  namespace :api do
    namespace :v1 do
      get 'home/index'
      post 'home/create'
      delete 'home/:id', to: 'home#destroy'
    end
  end
  # get 'fractions'
  root 'home#index'
  
  
  devise_scope :user do
    get '/users/sign_in' => 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
    #TODO: Ausloggen reparieren
    # get '/users/employees' => 'users#index'
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)
      can :manage, :all if user.role == "admin"
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fraction.rb
class Fraction < ApplicationRecord
end

app/models/price.rb
class Price < ApplicationRecord

    def priceindex
        @prices = Prices.all

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
   #      :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable, :rememberable,:authentication_keys => [:username]
  validates :username, uniqueness: true
  end

app/controllers/api/v1/prices_controller.rb
class Api::V1::HomeController < ApplicationController
before_action :set_price, only: [:show, :edit, :update, :destroy]

# GET /prices
# GET /prices.json
def index
    @prices = Price.all
    render json: @prices
end

# GET /prices/1
# GET /prices/1.json
def show
    if @price
    render json: @price
    else
    render json: @price.errors
    end
end

# GET /prices/new
def new
    @price = Price.new
end

# GET /prices/1/edit
def edit
end

# POST /prices
# POST /prices.json
def create
    @price = Price.new(price_params)


    if @price.save
    render json: @price
    else
    render json: @price.errors
    end
end

# PATCH/PUT /prices/1
# PATCH/PUT /prices/1.json
def update
end

# DELETE /prices/1
# DELETE /prices/1.json
def destroy
    @price.destroy

    render json: { notice: 'Price was successfully removed.' }
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
    @price = Price.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def price_params
    params.permit(:brand, :style, :country, :quantity)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/fractions_controller.rb
class FractionsController < ApplicationController
  before_action :set_fraction, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /fractions or /fractions.json
  def index
    @fractions = Fraction.all
  end

  # GET /fractions/1 or /fractions/1.json
  def show
  end

  # GET /fractions/new
  def new
    @fraction = Fraction.new
  end

  # GET /fractions/1/edit
  def edit
  end

  # POST /fractions or /fractions.json
  def create
    @fraction = Fraction.new(fraction_params)

    respond_to do |format|
      if @fraction.save
        format.html { redirect_to fraction_url(@fraction), notice: "Fraktion wurde erfolgreich erstellt." }
        format.json { render :show, status: :created, location: @fraction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fractions/1 or /fractions/1.json
  def update
    respond_to do |format|
      if @fraction.update(fraction_params)
        format.html { redirect_to fraction_url(@fraction), notice: "Fraktion wurde erfolgreich bearbeitet." }
        format.json { render :show, status: :ok, location: @fraction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fractions/1 or /fractions/1.json
  def destroy
    @fraction.destroy

    respond_to do |format|
      format.html { redirect_to fractions_url, notice: "Fraktion wurde erfolgreich gelöscht." }
      format.json { render json: Fraction.all, status: :ok}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fraction
      @fraction = Fraction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fraction_params
      params.require(:fraction).permit(:name, :primary, :secondary, :pearl, :smoke, :lights, :contract, :plate, :id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  # def pricelist
  #   @fractions = Fraction.all
  # end
end

app/controllers/pricelist_controller.rb
class PricelistController < ApplicationController
  def index
    @fractions = Hash[Fraction.all.map do |fraction|
      [
        fraction.name,
        {
          primary: fraction.primary,
          secondary: fraction.secondary,
          pearl: fraction.pearl,
          lights: fraction.lights,
          smoke: fraction.smoke,
          contract: fraction.contract,
          plate: fraction.plate
        }
      ]
    end]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        # @users = User.all
    end

    def update
        respond_to do |format|
            if @users.update(fraction_params)
            format.html { redirect_to user_url(@user), notice: "Mitarbeiter wurde erfolgreich bearbeitet." }
            format.json { render :show, status: :ok, location: @user }
            else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @user.errors, status: :unprocessable_entity }
        end
     end
    end
    # Set the user record before each action
    # before_action :set_user, only: [:show, :edit, :update, :destroy]
  
    # # User must authenticate to use all actions in the users controller  
    # #before_filter :authenticate_user!
  
    # def create
    #   if current_user.role = "superadmin" then
    #     @user = User.new(user_params)
    #     @user.password = Devise.friendly_token[0,20]
  
    #     respond_to do |format|
    #       if @user.save
    #         format.html { redirect_to @user, notice: 'User was successfully created.' }
    #         format.json { render action: 'show', status: :created, location: @user }
    #       else
    #         format.html { render action: 'new' }
    #         format.json { render json: @user.errors, status: :unprocessable_entity }
    #       end
    #     end
    #   else
    #     format.html { redirect_to @user, notice: 'You do not have sufficient rights to set up a new user.' }
    #   end
    # end
  
    # private
  
    # # Use callbacks to share common setup or constraints between actions.
    # # def set_user
    # #   @user = User.find(params[:username])
  
    # #   rescue ActiveRecord::RecordNotFound  
    # #   flash[:notice] = "User record does not exist"
    # #   redirect_to users_url
    # # end
  end

app/helpers/api/v1/prices_helper.rb
module Api::V1::PricesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fractions_helper.rb
module FractionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pricelist_helper.rb
module PricelistHelper
end

app/views/fractions/_form.html.erb
<%= form_with(model: fraction) do |form| %>
  <% if fraction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fraction.errors.count, "error") %> prohibited this fraction from being saved:</h2>

      <ul>
        <% fraction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div>
    <%= form.label :name, class:"form-label fw-bold" %>
    <%= form.text_field :name, class:"form-control"  %>
  </div>

  <div>
    <%= form.label :primary, class:"form-label fw-bold" %>
    <%= form.text_field :primary, class:"form-control"  %>
  </div>

  <div>
    <%= form.label :secondary, class:"form-label fw-bold" %>
    <%= form.text_field :secondary, class:"form-control"  %>
  </div>

  <div>
    <%= form.label :pearl, class:"form-label fw-bold" %>
    <%= form.text_field :pearl, class:"form-control"  %>
  </div>

  <div>
    <%= form.label :smoke, class:"form-label fw-bold" %>
    <%= form.text_field :smoke, class:"form-control"  %>
  </div>

  <div>
    <%= form.label :lights, class:"form-label fw-bold" %>
    <%= form.text_field :lights, class:"form-control"  %>
  </div>
  <br/>
  <div>
    <%= form.label :contract, class:"form-label fw-bold" %>
    <%= form.date_field :contract%>
  </div>

  <div>
    <%= form.label :plate, class:"form-label fw-bold" %>
    <%= form.check_box :plate %>
  </div>

  <div>
    <%= form.submit class:"btn btn-warning btn-sm"%>
  </div>
<% end %>

app/views/fractions/_fraction.html.erb
<div id="<%= dom_id fraction %>">

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= fraction.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Vertrag bis: <%= fraction.contract %></h6>
    
     <p>
    <strong>Primary:</strong>
    <%= fraction.primary %>
  </p>

  <p>
    <strong>Secondary:</strong>
    <%= fraction.secondary %>
  </p>

  <p>
    <strong>Pearl:</strong>
    <%= fraction.pearl %>
  </p>

  <p>
    <strong>Smoke:</strong>
    <%= fraction.smoke %>
  </p>

  <p>
    <strong>Lights:</strong>
    <%= fraction.lights %>
  </p>

  <p>
    <strong>Contract:</strong>
    <%= fraction.contract %>
  </p>

  <p>
    <strong>Plate:</strong>
    <%= fraction.plate %>
  </p>
    <%# <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a> %>
  </div>
  
</div>
  <br/>


</div>

app/views/fractions/edit.html.erb
<h1>Editing fraction</h1>

<%= render "form", fraction: @fraction %>

<br>

<div>
  <%= link_to "Show this fraction", @fraction, class:"btn btn-outline-info btn-sm" %> 
  <%= link_to "Back to fractions", fractions_path, class:"btn btn-outline-secondary btn-sm" %>
</div>

app/views/fractions/index.html.erb
<h1>Fraktionen</h1>

<table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Primärfarbe</th>
        <th scope="col">Sekundärfarbe</th>
        <th scope="col">Perleffekt</th>
        <th scope="col">Reifenrauch</th>
        <th scope="col">Unterbodenbelichtung</th>
        <th scope="col">Vertrag bis</th>
        <th scope="col">inkl. Kennzeichen</th>
        <th> </th>
        <th> </th>
        <th> </th>
      <tr>
    </thead>
    <tbody>
      <% @fractions.each do |fraction| %>
        
        <tr>
                   
          <td><%= fraction.name %></td>
          <td><%= fraction.primary %></td>
          <td><%= fraction.secondary %></td>
          <td><%= fraction.pearl %></td>
          <td><%= fraction.smoke %></td>
          <td><%= fraction.lights %></td>
          <td><%= fraction.contract %></td>
          <td><%= fraction.plate %></td>
          <td><%= link_to 'Zeigen', fraction, class: "btn btn-outline-info btn-sm" %></td>
          <td><%= link_to 'Bearbeiten', edit_fraction_path(fraction), class: "btn btn-outline-warning btn-sm" %></td>
          <td><%= link_to 'Löschen', fraction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          
        </tr>
       <% end %>
      
    </tbody>
  </table>

  <br/>

  <%= link_to 'Neue Fraktion', new_fraction_path, class:"btn btn-secondary" %>

app/views/fractions/new.html.erb
<h1>New fraction</h1>

<%= render "form", fraction: @fraction %>

<br>

<div>
  <%= link_to "Back to fractions", fractions_path %>
</div>

app/views/fractions/show.html.erb
<%= render @fraction %>

<div>
  <%= link_to "Edit this fraction", edit_fraction_path(@fraction), class:"btn btn-outline-warning btn-sm"%>
  <%= link_to "Back to fractions", fractions_path, class:"btn btn-outline-info btn-sm" %>
  <br/><br/>
  <%= button_to "Destroy this fraction", @fraction, method: :delete, class:"btn btn-outline-danger btn-sm"%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsxybzju0CQKdwsj4P1SY6PgoIc4GblhnIFw&usqp=CAU.svg", style:'width:50px; height:50px'), root_path, class:"d-inline-block align-text-top"%>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
          
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Preisliste', pricelist_index_path, class:"nav-link"%>
        </li>
        <%# TODO: rauslöschen %>
        <li class="nav-item">
            <%= link_to 'Fraktionen', fractions_path, class:"nav-link"%>
        </li>
        <% if current_user.try(:admin?)%>
        <li class="nav-item">
            <%= link_to 'Mitarbeitermanagement', users_path, class:"nav-link"%>
        </li>
        <% end%>
        <li class="nav-item">
            <%= link_to "Ausloggen", destroy_user_session_path, :method => :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%# link_to 'Neuer Mitarbeiter', new_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%# link_to 'Mitarbeiter bearbeiten', edit_user_registration_path, class:"nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Einloggen', new_user_session_path, class:"nav-link"%>
          </li>
        <% end %>
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<%#<%= stylesheet_link_tag "home", "data-turbo-track": "reload" %>

<%#<% if user_signed_in? %>

<%#<% else %>

<%#HOMEPAGE NOT LOGGED IN

<% end %>
<div id="root"></div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Huchos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  
    <%= render 'home/header' %>
    <div class="container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
      <% end %>
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
    <%# <%= javascript_importmap_tags %> 
    <%# <%= yield :head %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Mitarbeiter</h1>

<table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Rolle</th>
        <th scope="col"></th>
      <tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        
        <tr>
                   
          <td><%= user.username %></td> 
          <% if user.superadmin?%>
          <td>Superadmin</td>
          <% elsif user.admin?%>
          <td>Chef</td>
          <% elsif user.employee?%>
          <td>Angestellter</td>
          <% elsif user.intern?%>
          <td>Praktikant</td>
          <% end %>
          <td><%= link_to 'Bearbeiten', root_path , class: "btn btn-outline-warning btn-sm" %>
          <td><%= link_to 'Löschen', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
           
        </tr>
       <% end %>
      
    </tbody>
  </table>

  <br/>

  <%= link_to 'Neuer Mitarbeiter', root_path, class:"btn btn-secondary" %>

app/views/users/show.html.erb
<%= "hello world" %>